# Generated by Django 5.2.7 on 2025-11-05 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-created_at', 'name']},
        ),
    ]
