# Generated by Django 5.2.7 on 2025-11-05 12:51

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_tag_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='bio',
            field=models.TextField(blank=True, help_text='A brief description or biography of the blog', verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the blog was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(help_text='The title of the blog', max_length=200, verbose_name='Blog Title'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when the blog was last updated', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='user',
            field=models.OneToOneField(help_text='The user who owns this blog. Each user can have only one blog.', on_delete=django.db.models.deletion.CASCADE, related_name='blog', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='blog',
            field=models.ForeignKey(help_text='The blog this post belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.blog', verbose_name='Blog'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(help_text='The main content of the post (HTML format)', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, help_text='Cover image for the post', null=True, upload_to='posts/covers/', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the post was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, help_text='A short summary or excerpt of the post', verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Whether the post is published and visible to the public', verbose_name='Is Published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='The date and time when the post was published', null=True, verbose_name='Published At'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the title. Auto-generated if not provided.', max_length=260, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags associated with this post', related_name='posts', to='core.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='The title of the post', max_length=250, verbose_name='Post Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when the post was last updated', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the tag was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='The name of the tag. Must be unique.', max_length=50, unique=True, verbose_name='Tag Name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when the tag was last updated', verbose_name='Updated At'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['user'], name='core_blog_user_id_f994f9_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['-created_at'], name='core_blog_created_a03b6c_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['blog'], name='core_post_blog_id_9a727e_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_published'], name='core_post_is_publ_01104b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['slug'], name='core_post_slug_474b18_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-published_at', '-created_at'], name='core_post_publish_f32be3_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='core_tag_name_102daa_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['-created_at', 'name'], name='core_tag_created_36a35d_idx'),
        ),
    ]
