# Generated by Django 5.2.7 on 2025-11-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='bio',
            field=models.TextField(),
        ),
    ]
